### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by wyleyr**
Hi Richard,

I've made a bunch of corrections to the text during the first few weeks of the course. Most deal with typos or corrections to the solutions manual; some are slightly more significant, like removing terminology from other versions of the text.  I've merged with your current master, so these changes should apply automatically; let me know if there's any other changes you'd like me to make before merging.

Best,
Richard

### CODE REVIEW

**Comment by rzach** [comment]
Thanks so much for all of this. I'll probably have to cherry-pick some of these commits rather than apply all of them.  @AThomasBolduc is working on getting the solutions to the missing exercises into the solutions booklet, so hopefully we won't need the renumbering stuff in the solutions.  And I think we want American spelling (ie "symbolize" not "symbolise") but it's quite likely we didn't properly change that from the Cambridge version uniformly.

**Comment by wyleyr** [comment]
Sure thing. Cherry-pick away!  Sorry to send such a big pull request...if there is a branch somewhere that I should be tracking, let me know, and I can keep up to date with it and send requests in smaller chunks.

**Comment by wyleyr** [comment]
I've just added a few more fixes for problems that Rachel noticed.

By the way, I think Rachel is going to tell her students to order the book in about a week. If there's any chance you have time to pull in the corrections and upload the new PDF to Lulu/Amazon this week, I'm sure she and her students would really appreciate it!

**Comment by rzach** [comment]
Turns out cherry-picking isn't so easy because most of your commits applied to a previous version. So I have to wait until @AThomasBolduc has his corrections to the solutions ready and then fix the conflicts by hand. (Planning to do this asap though so a new version is ready this week.)

**Comment by rzach** [comment]
Instead of that ^ we'll figure out the corrections to the solutions.

**Pull request merged**
